# Generated by Django 4.2.7 on 2025-11-21 03:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="NaturalLanguageQuery",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "deleted_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Fecha de eliminación"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "query_text",
                    models.TextField(
                        help_text="Texto original ingresado por el usuario (voz o escrito)"
                    ),
                ),
                (
                    "language",
                    models.CharField(
                        default="es",
                        help_text="Idioma del query (es, en, etc.)",
                        max_length=10,
                    ),
                ),
                (
                    "input_method",
                    models.CharField(
                        choices=[("text", "Texto"), ("voice", "Voz")],
                        default="text",
                        max_length=20,
                    ),
                ),
                (
                    "generated_sql",
                    models.TextField(
                        blank=True, help_text="Consulta SQL generada por IA"
                    ),
                ),
                (
                    "inferred_params",
                    models.JSONField(
                        default=dict,
                        help_text="Parámetros extraídos del lenguaje natural",
                    ),
                ),
                (
                    "confidence_score",
                    models.FloatField(
                        default=0.0,
                        help_text="Puntuación de confianza (0-1) de la interpretación",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pendiente"),
                            ("parsed", "Parseado"),
                            ("validated", "Validado"),
                            ("failed", "Fallido"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("error_message", models.TextField(blank=True)),
                (
                    "ai_model",
                    models.CharField(
                        default="gpt-4",
                        help_text="Modelo de IA usado para parsear (gpt-4, claude, bedrock, etc.)",
                        max_length=50,
                    ),
                ),
                (
                    "processing_time_ms",
                    models.IntegerField(
                        blank=True,
                        help_text="Tiempo de procesamiento en milisegundos",
                        null=True,
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(class)s_set",
                        to="core.tenant",
                        verbose_name="Tenant",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="nl_queries",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Consulta en Lenguaje Natural",
                "verbose_name_plural": "Consultas en Lenguaje Natural",
                "db_table": "nl_query",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="QueryExecution",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "deleted_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Fecha de eliminación"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "executed_sql",
                    models.TextField(
                        help_text="SQL realmente ejecutado (puede incluir límites, etc.)"
                    ),
                ),
                (
                    "result_count",
                    models.IntegerField(
                        default=0, help_text="Número de filas retornadas"
                    ),
                ),
                (
                    "result_data",
                    models.JSONField(
                        default=dict,
                        help_text="Datos del resultado (puede ser un subset)",
                    ),
                ),
                (
                    "execution_time_ms",
                    models.IntegerField(
                        help_text="Tiempo de ejecución de la consulta en ms"
                    ),
                ),
                (
                    "output_format",
                    models.CharField(
                        choices=[
                            ("json", "JSON"),
                            ("csv", "CSV"),
                            ("excel", "Excel"),
                            ("pdf", "PDF"),
                        ],
                        default="json",
                        max_length=20,
                    ),
                ),
                (
                    "row_limit",
                    models.IntegerField(
                        default=100, help_text="Límite de filas aplicado en la consulta"
                    ),
                ),
                (
                    "file_path",
                    models.CharField(
                        blank=True,
                        help_text="Ruta al archivo generado (para CSV, Excel, PDF)",
                        max_length=500,
                    ),
                ),
                ("file_size_bytes", models.BigIntegerField(blank=True, null=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pendiente"),
                            ("executing", "Ejecutando"),
                            ("completed", "Completado"),
                            ("failed", "Fallido"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("error_message", models.TextField(blank=True)),
                (
                    "nl_query",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="executions",
                        to="reports_ai.naturallanguagequery",
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(class)s_set",
                        to="core.tenant",
                        verbose_name="Tenant",
                    ),
                ),
            ],
            options={
                "verbose_name": "Ejecución de Consulta",
                "verbose_name_plural": "Ejecuciones de Consultas",
                "db_table": "query_execution",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="QueryTemplate",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "deleted_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Fecha de eliminación"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=200)),
                ("description", models.TextField(blank=True)),
                (
                    "example_phrases",
                    models.JSONField(
                        default=list,
                        help_text="Lista de frases ejemplo que usan esta plantilla",
                    ),
                ),
                (
                    "sql_template",
                    models.TextField(
                        help_text="Template SQL con placeholders: {table}, {date_from}, etc."
                    ),
                ),
                (
                    "required_params",
                    models.JSONField(
                        default=list,
                        help_text="Lista de parámetros requeridos: ['table', 'date_from', ...]",
                    ),
                ),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("patients", "Pacientes"),
                            ("clinical_forms", "Formularios Clínicos"),
                            ("documents", "Documentos"),
                            ("users", "Usuarios"),
                            ("analytics", "Analíticas"),
                        ],
                        default="patients",
                        max_length=50,
                    ),
                ),
                ("usage_count", models.IntegerField(default=0)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(class)s_set",
                        to="core.tenant",
                        verbose_name="Tenant",
                    ),
                ),
            ],
            options={
                "verbose_name": "Plantilla de Consulta",
                "verbose_name_plural": "Plantillas de Consultas",
                "db_table": "query_template",
                "ordering": ["-usage_count", "name"],
            },
        ),
        migrations.CreateModel(
            name="QueryFeedback",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "deleted_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Fecha de eliminación"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "rating",
                    models.IntegerField(
                        choices=[
                            (1, "⭐ Muy malo"),
                            (2, "⭐⭐ Malo"),
                            (3, "⭐⭐⭐ Regular"),
                            (4, "⭐⭐⭐⭐ Bueno"),
                            (5, "⭐⭐⭐⭐⭐ Excelente"),
                        ],
                        help_text="Calificación de 1-5 estrellas",
                    ),
                ),
                (
                    "was_useful",
                    models.BooleanField(
                        default=True, help_text="¿El resultado respondió la pregunta?"
                    ),
                ),
                (
                    "comments",
                    models.TextField(
                        blank=True, help_text="Comentarios adicionales del usuario"
                    ),
                ),
                (
                    "suggested_sql",
                    models.TextField(
                        blank=True, help_text="SQL sugerido por el usuario como mejora"
                    ),
                ),
                (
                    "execution",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="feedback",
                        to="reports_ai.queryexecution",
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(class)s_set",
                        to="core.tenant",
                        verbose_name="Tenant",
                    ),
                ),
            ],
            options={
                "verbose_name": "Feedback de Consulta",
                "verbose_name_plural": "Feedbacks de Consultas",
                "db_table": "query_feedback",
                "ordering": ["-created_at"],
            },
        ),
        migrations.AddIndex(
            model_name="queryexecution",
            index=models.Index(
                fields=["nl_query", "-created_at"],
                name="query_execu_nl_quer_3e9027_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="queryexecution",
            index=models.Index(fields=["status"], name="query_execu_status_1824be_idx"),
        ),
        migrations.AddIndex(
            model_name="naturallanguagequery",
            index=models.Index(
                fields=["user", "-created_at"], name="nl_query_user_id_84a07c_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="naturallanguagequery",
            index=models.Index(fields=["status"], name="nl_query_status_1512f5_idx"),
        ),
    ]
