# Generated by Django 4.2.7 on 2025-10-29 02:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("core", "0001_initial"),
        ("patients", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="ClinicalRecord",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "deleted_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Fecha de eliminación"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "record_number",
                    models.CharField(
                        help_text="Se genera automáticamente",
                        max_length=100,
                        verbose_name="Número de expediente",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("active", "Activa"),
                            ("archived", "Archivada"),
                            ("closed", "Cerrada"),
                        ],
                        default="active",
                        max_length=50,
                        verbose_name="Estado",
                    ),
                ),
                (
                    "blood_type",
                    models.CharField(
                        blank=True, max_length=10, verbose_name="Tipo de sangre"
                    ),
                ),
                (
                    "allergies",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text='[{"allergen": "...", "severity": "...", "reaction": "..."}]',
                        verbose_name="Alergias",
                    ),
                ),
                (
                    "chronic_conditions",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text='["Diabetes tipo 2", "Hipertensión"]',
                        verbose_name="Condiciones crónicas",
                    ),
                ),
                (
                    "medications",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text='[{"name": "...", "dose": "...", "frequency": "..."}]',
                        verbose_name="Medicamentos actuales",
                    ),
                ),
                (
                    "family_history",
                    models.TextField(
                        blank=True, verbose_name="Antecedentes familiares"
                    ),
                ),
                (
                    "social_history",
                    models.TextField(blank=True, verbose_name="Antecedentes sociales"),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="clinical_records_created",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Creado por",
                    ),
                ),
                (
                    "patient",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="patients.patient",
                        verbose_name="Paciente",
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(class)s_set",
                        to="core.tenant",
                        verbose_name="Tenant",
                    ),
                ),
            ],
            options={
                "verbose_name": "Historia Clínica",
                "verbose_name_plural": "Historias Clínicas",
                "db_table": "clinical_record",
                "indexes": [
                    models.Index(
                        fields=["tenant", "patient"],
                        name="clinical_re_tenant__759d97_idx",
                    ),
                    models.Index(
                        fields=["record_number"], name="clinical_re_record__b6cfd6_idx"
                    ),
                    models.Index(
                        fields=["status"], name="clinical_re_status_faf8a7_idx"
                    ),
                ],
                "unique_together": {("tenant", "record_number")},
            },
        ),
    ]
