# Generated by Django 4.2.7 on 2025-11-05 12:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("patients", "0001_initial"),
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="ClinicalRecord",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "deleted_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Fecha de eliminación"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "record_number",
                    models.CharField(
                        help_text="Se genera automáticamente",
                        max_length=100,
                        verbose_name="Número de expediente",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("active", "Activa"),
                            ("archived", "Archivada"),
                            ("closed", "Cerrada"),
                        ],
                        default="active",
                        max_length=50,
                        verbose_name="Estado",
                    ),
                ),
                (
                    "blood_type",
                    models.CharField(
                        blank=True, max_length=10, verbose_name="Tipo de sangre"
                    ),
                ),
                (
                    "allergies",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text='[{"allergen": "...", "severity": "...", "reaction": "..."}]',
                        verbose_name="Alergias",
                    ),
                ),
                (
                    "chronic_conditions",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text='["Diabetes tipo 2", "Hipertensión"]',
                        verbose_name="Condiciones crónicas",
                    ),
                ),
                (
                    "medications",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text='[{"name": "...", "dose": "...", "frequency": "..."}]',
                        verbose_name="Medicamentos actuales",
                    ),
                ),
                (
                    "family_history",
                    models.TextField(
                        blank=True, verbose_name="Antecedentes familiares"
                    ),
                ),
                (
                    "social_history",
                    models.TextField(blank=True, verbose_name="Antecedentes sociales"),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="clinical_records_created",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Creado por",
                    ),
                ),
                (
                    "patient",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="patients.patient",
                        verbose_name="Paciente",
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(class)s_set",
                        to="core.tenant",
                        verbose_name="Tenant",
                    ),
                ),
            ],
            options={
                "verbose_name": "Historia Clínica",
                "verbose_name_plural": "Historias Clínicas",
                "db_table": "clinical_record",
            },
        ),
        migrations.CreateModel(
            name="ClinicalForm",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "deleted_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Fecha de eliminación"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "form_type",
                    models.CharField(
                        choices=[
                            ("triage", "Triaje"),
                            ("consultation", "Consulta Médica"),
                            ("evolution", "Nota de Evolución"),
                            ("prescription", "Receta Médica"),
                            ("lab_order", "Orden de Laboratorio"),
                            ("imaging_order", "Orden de Imagenología"),
                            ("procedure", "Procedimiento"),
                            ("discharge", "Alta Médica"),
                            ("referral", "Referencia"),
                            ("other", "Otro"),
                        ],
                        max_length=100,
                        verbose_name="Tipo de formulario",
                    ),
                ),
                (
                    "form_template_id",
                    models.UUIDField(
                        blank=True,
                        help_text="Si se usó una plantilla predefinida",
                        null=True,
                        verbose_name="ID de plantilla",
                    ),
                ),
                (
                    "form_data",
                    models.JSONField(
                        default=dict,
                        help_text="Estructura JSON flexible según el tipo de formulario",
                        verbose_name="Datos del formulario",
                    ),
                ),
                (
                    "doctor_name",
                    models.CharField(
                        blank=True,
                        help_text="Opcional, se puede tomar del usuario",
                        max_length=255,
                        verbose_name="Nombre del doctor",
                    ),
                ),
                (
                    "doctor_specialty",
                    models.CharField(
                        blank=True,
                        max_length=100,
                        verbose_name="Especialidad del doctor",
                    ),
                ),
                (
                    "form_date",
                    models.DateTimeField(
                        help_text="Fecha en que se llenó el formulario",
                        verbose_name="Fecha del formulario",
                    ),
                ),
                (
                    "clinical_record",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="forms",
                        to="clinical_records.clinicalrecord",
                        verbose_name="Historia Clínica",
                    ),
                ),
                (
                    "filled_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="filled_forms",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Llenado por",
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(class)s_set",
                        to="core.tenant",
                        verbose_name="Tenant",
                    ),
                ),
            ],
            options={
                "verbose_name": "Formulario Clínico",
                "verbose_name_plural": "Formularios Clínicos",
                "db_table": "clinical_form",
                "ordering": ["-form_date"],
            },
        ),
        migrations.AddIndex(
            model_name="clinicalrecord",
            index=models.Index(
                fields=["tenant", "patient"], name="clinical_re_tenant__759d97_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="clinicalrecord",
            index=models.Index(
                fields=["record_number"], name="clinical_re_record__b6cfd6_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="clinicalrecord",
            index=models.Index(fields=["status"], name="clinical_re_status_faf8a7_idx"),
        ),
        migrations.AlterUniqueTogether(
            name="clinicalrecord",
            unique_together={("tenant", "record_number")},
        ),
        migrations.AddIndex(
            model_name="clinicalform",
            index=models.Index(
                fields=["tenant", "clinical_record"],
                name="clinical_fo_tenant__7172d1_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="clinicalform",
            index=models.Index(
                fields=["form_type"], name="clinical_fo_form_ty_141705_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="clinicalform",
            index=models.Index(
                fields=["-form_date"], name="clinical_fo_form_da_d805fd_idx"
            ),
        ),
    ]
