# Generated by Django 4.2.7 on 2025-11-03 21:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("core", "0001_initial"),
        ("clinical_records", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="ClinicalForm",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "deleted_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Fecha de eliminación"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "form_type",
                    models.CharField(
                        choices=[
                            ("triage", "Triaje"),
                            ("consultation", "Consulta Médica"),
                            ("evolution", "Nota de Evolución"),
                            ("prescription", "Receta Médica"),
                            ("lab_order", "Orden de Laboratorio"),
                            ("imaging_order", "Orden de Imagenología"),
                            ("procedure", "Procedimiento"),
                            ("discharge", "Alta Médica"),
                            ("referral", "Referencia"),
                            ("other", "Otro"),
                        ],
                        max_length=100,
                        verbose_name="Tipo de formulario",
                    ),
                ),
                (
                    "form_template_id",
                    models.UUIDField(
                        blank=True,
                        help_text="Si se usó una plantilla predefinida",
                        null=True,
                        verbose_name="ID de plantilla",
                    ),
                ),
                (
                    "form_data",
                    models.JSONField(
                        default=dict,
                        help_text="Estructura JSON flexible según el tipo de formulario",
                        verbose_name="Datos del formulario",
                    ),
                ),
                (
                    "doctor_name",
                    models.CharField(
                        blank=True,
                        help_text="Opcional, se puede tomar del usuario",
                        max_length=255,
                        verbose_name="Nombre del doctor",
                    ),
                ),
                (
                    "doctor_specialty",
                    models.CharField(
                        blank=True,
                        max_length=100,
                        verbose_name="Especialidad del doctor",
                    ),
                ),
                (
                    "form_date",
                    models.DateTimeField(
                        help_text="Fecha en que se llenó el formulario",
                        verbose_name="Fecha del formulario",
                    ),
                ),
                (
                    "clinical_record",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="forms",
                        to="clinical_records.clinicalrecord",
                        verbose_name="Historia Clínica",
                    ),
                ),
                (
                    "filled_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="filled_forms",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Llenado por",
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(class)s_set",
                        to="core.tenant",
                        verbose_name="Tenant",
                    ),
                ),
            ],
            options={
                "verbose_name": "Formulario Clínico",
                "verbose_name_plural": "Formularios Clínicos",
                "db_table": "clinical_form",
                "ordering": ["-form_date"],
                "indexes": [
                    models.Index(
                        fields=["tenant", "clinical_record"],
                        name="clinical_fo_tenant__7172d1_idx",
                    ),
                    models.Index(
                        fields=["form_type"], name="clinical_fo_form_ty_141705_idx"
                    ),
                    models.Index(
                        fields=["-form_date"], name="clinical_fo_form_da_d805fd_idx"
                    ),
                ],
            },
        ),
    ]
