# Generated by Django 4.2.7 on 2025-11-03 19:29

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="userpreferences",
            name="font_family",
            field=models.CharField(
                choices=[
                    ("inter", "Inter"),
                    ("roboto", "Roboto"),
                    ("open-sans", "Open Sans"),
                    ("lato", "Lato"),
                    ("montserrat", "Montserrat"),
                ],
                default="inter",
                max_length=30,
                verbose_name="Tipografía",
            ),
        ),
        migrations.AddField(
            model_name="userpreferences",
            name="font_size",
            field=models.CharField(
                choices=[
                    ("small", "Pequeño"),
                    ("medium", "Mediano"),
                    ("large", "Grande"),
                    ("extra-large", "Extra Grande"),
                ],
                default="medium",
                max_length=20,
                verbose_name="Tamaño de fuente",
            ),
        ),
        migrations.AlterField(
            model_name="userpreferences",
            name="theme",
            field=models.CharField(
                choices=[
                    ("light", "Claro"),
                    ("dark", "Oscuro"),
                    ("blue", "Azul"),
                    ("green", "Verde"),
                    ("purple", "Púrpura"),
                ],
                default="light",
                max_length=20,
                verbose_name="Tema",
            ),
        ),
    ]
