# Generated by Django 4.2.7 on 2025-11-03 20:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0001_initial"),
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="permission",
            name="deleted_at",
        ),
        migrations.RemoveField(
            model_name="role",
            name="deleted_at",
        ),
        migrations.AlterField(
            model_name="permission",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, verbose_name="Creado"),
        ),
        migrations.AlterField(
            model_name="permission",
            name="tenant",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="permissions",
                to="core.tenant",
                verbose_name="Tenant (NULL para permisos globales)",
            ),
        ),
        migrations.AlterField(
            model_name="permission",
            name="updated_at",
            field=models.DateTimeField(auto_now=True, verbose_name="Actualizado"),
        ),
        migrations.AlterField(
            model_name="role",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, verbose_name="Creado"),
        ),
        migrations.AlterField(
            model_name="role",
            name="tenant",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="roles",
                to="core.tenant",
                verbose_name="Tenant (NULL para roles globales)",
            ),
        ),
        migrations.AlterField(
            model_name="role",
            name="updated_at",
            field=models.DateTimeField(auto_now=True, verbose_name="Actualizado"),
        ),
        migrations.AddIndex(
            model_name="role",
            index=models.Index(fields=["tenant"], name="roles_tenant__94d729_idx"),
        ),
        migrations.AddIndex(
            model_name="role",
            index=models.Index(fields=["name"], name="roles_name_a96913_idx"),
        ),
    ]
