# Generated by Django 4.2.7 on 2025-11-07 16:39

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='personal_email',
            field=models.EmailField(
                blank=True,
                max_length=254,
                null=True,
                verbose_name='Email personal'
            ),
        ),
    ]
