# Generated by Django 4.2.7 on 2025-11-10 04:43

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0002_add_personal_email"),
        ("accounts", "0002_remove_user_personal_email"),
    ]

    operations = []
