# Generated by Django 4.2.7 on 2025-11-03 22:51

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        (
            "accounts",
            "0002_remove_permission_deleted_at_remove_role_deleted_at_and_more",
        ),
        ("accounts", "0002_userpreferences_font_family_and_more"),
    ]

    operations = []
