# Generated by Django 4.2.7 on 2025-11-10 04:43

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0003_merge_20251110_0043"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="user",
            name="personal_email",
        ),
    ]
