# Generated by Django 4.2.7 on 2025-11-17 03:32

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0004_remove_user_personal_email"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="fcm_token",
            field=models.CharField(
                blank=True,
                max_length=255,
                null=True,
                verbose_name="Token FCM (Firebase)",
            ),
        ),
    ]
