# Generated by Django 4.2.7 on 2025-11-17 06:56

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0005_user_fcm_token"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="personal_email",
            field=models.EmailField(
                blank=True,
                help_text="Email de contacto real, puede tener dominio del tenant",
                max_length=254,
                null=True,
                verbose_name="Email personal",
            ),
        ),
    ]
