# Generated by Django 4.2.7 on 2025-11-18 13:50

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0006_user_personal_email"),
    ]

    operations = [
        migrations.AlterField(
            model_name="userpreferences",
            name="theme",
            field=models.CharField(
                choices=[
                    ("light", "Claro"),
                    ("dark", "Oscuro"),
                    ("blue", "Azul"),
                    ("green", "Verde"),
                    ("purple", "Púrpura"),
                    ("yellow", "Amarillo"),
                ],
                default="light",
                max_length=20,
                verbose_name="Tema",
            ),
        ),
    ]
