# Generated by Django 4.2.7 on 2025-11-05 12:13

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="BackupJob",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "backup_type",
                    models.CharField(
                        choices=[
                            ("full", "Completo"),
                            ("incremental", "Incremental"),
                            ("differential", "Diferencial"),
                        ],
                        default="full",
                        max_length=50,
                    ),
                ),
                (
                    "backup_scope",
                    models.CharField(
                        choices=[
                            ("tenant", "Por Tenant"),
                            ("system", "Sistema Completo"),
                        ],
                        default="system",
                        max_length=100,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pendiente"),
                            ("processing", "Procesando"),
                            ("completed", "Completado"),
                            ("failed", "Fallido"),
                        ],
                        default="pending",
                        max_length=50,
                    ),
                ),
                ("storage_location", models.CharField(blank=True, max_length=500)),
                ("backup_size_bytes", models.BigIntegerField(null=True)),
                ("includes_database", models.BooleanField(default=True)),
                ("includes_files", models.BooleanField(default=True)),
                ("includes_audit_logs", models.BooleanField(default=True)),
                ("is_encrypted", models.BooleanField(default=True)),
                ("encryption_key_id", models.CharField(blank=True, max_length=255)),
                ("scheduled", models.BooleanField(default=False)),
                ("schedule_cron", models.CharField(blank=True, max_length=100)),
                ("can_restore", models.BooleanField(default=True)),
                ("retention_until", models.DateField(blank=True, null=True)),
                ("started_at", models.DateTimeField(null=True)),
                ("completed_at", models.DateTimeField(null=True)),
                ("error_message", models.TextField(blank=True)),
                ("retry_count", models.IntegerField(default=0)),
                ("metadata", models.JSONField(default=dict)),
                (
                    "tenant",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="backups",
                        to="core.tenant",
                    ),
                ),
            ],
            options={
                "db_table": "backup_job",
                "ordering": ["-created_at"],
            },
        ),
    ]
