# Generated by Django 4.2.7 on 2025-10-29 02:28

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Tenant",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        max_length=200, verbose_name="Nombre de la institución"
                    ),
                ),
                (
                    "slug",
                    models.SlugField(
                        max_length=100, unique=True, verbose_name="Slug único"
                    ),
                ),
                (
                    "subdomain",
                    models.CharField(
                        max_length=100, unique=True, verbose_name="Subdominio"
                    ),
                ),
                (
                    "subscription_plan",
                    models.CharField(
                        choices=[
                            ("basic", "Basic"),
                            ("pro", "Pro"),
                            ("enterprise", "Enterprise"),
                        ],
                        default="basic",
                        max_length=20,
                        verbose_name="Plan de suscripción",
                    ),
                ),
                (
                    "subscription_status",
                    models.CharField(
                        choices=[
                            ("active", "Activo"),
                            ("suspended", "Suspendido"),
                            ("trial", "Prueba"),
                            ("cancelled", "Cancelado"),
                        ],
                        default="trial",
                        max_length=20,
                        verbose_name="Estado de suscripción",
                    ),
                ),
                (
                    "subscription_start",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Inicio de suscripción"
                    ),
                ),
                (
                    "subscription_end",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Fin de suscripción"
                    ),
                ),
                (
                    "email",
                    models.EmailField(max_length=254, verbose_name="Email de contacto"),
                ),
                (
                    "phone",
                    models.CharField(
                        blank=True, max_length=20, verbose_name="Teléfono"
                    ),
                ),
                ("address", models.TextField(blank=True, verbose_name="Dirección")),
                (
                    "settings",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        verbose_name="Configuraciones personalizadas",
                    ),
                ),
                (
                    "max_users",
                    models.IntegerField(default=10, verbose_name="Máximo de usuarios"),
                ),
                (
                    "max_storage_gb",
                    models.IntegerField(
                        default=5, verbose_name="Máximo de almacenamiento (GB)"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
            ],
            options={
                "verbose_name": "Tenant",
                "verbose_name_plural": "Tenants",
                "db_table": "tenants",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(fields=["slug"], name="tenants_slug_3181c2_idx"),
                    models.Index(
                        fields=["subdomain"], name="tenants_subdoma_69cf01_idx"
                    ),
                    models.Index(
                        fields=["subscription_status"],
                        name="tenants_subscri_f58e68_idx",
                    ),
                ],
            },
        ),
    ]
