# Generated by Django 4.2.7 on 2025-11-05 12:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("core", "0001_initial"),
        ("clinical_records", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="ClinicalDocument",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "deleted_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Fecha de eliminación"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "document_type",
                    models.CharField(
                        choices=[
                            ("consultation", "Consulta"),
                            ("lab_result", "Resultado de Laboratorio"),
                            ("imaging_report", "Informe de Imagen"),
                            ("prescription", "Receta"),
                            ("surgical_note", "Nota Quirúrgica"),
                            ("discharge_summary", "Resumen de Alta"),
                            ("consent_form", "Consentimiento Informado"),
                            ("progress_note", "Nota de Evolución"),
                            ("referral", "Referencia"),
                        ],
                        max_length=100,
                        verbose_name="Tipo de documento",
                    ),
                ),
                ("title", models.CharField(max_length=255, verbose_name="Título")),
                (
                    "description",
                    models.TextField(blank=True, verbose_name="Descripción"),
                ),
                (
                    "document_date",
                    models.DateTimeField(
                        help_text="Fecha del evento médico",
                        verbose_name="Fecha del documento",
                    ),
                ),
                (
                    "specialty",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="Especialidad"
                    ),
                ),
                (
                    "doctor_name",
                    models.CharField(
                        blank=True, max_length=255, verbose_name="Nombre del médico"
                    ),
                ),
                (
                    "doctor_license",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="Matrícula del médico"
                    ),
                ),
                (
                    "content",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="JSON con el contenido del documento",
                        verbose_name="Contenido estructurado",
                    ),
                ),
                (
                    "file_path",
                    models.CharField(
                        blank=True,
                        max_length=500,
                        verbose_name="Ruta del archivo en S3",
                    ),
                ),
                (
                    "file_name",
                    models.CharField(
                        blank=True, max_length=255, verbose_name="Nombre del archivo"
                    ),
                ),
                (
                    "file_size_bytes",
                    models.BigIntegerField(
                        blank=True, null=True, verbose_name="Tamaño del archivo (bytes)"
                    ),
                ),
                (
                    "mime_type",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="Tipo MIME"
                    ),
                ),
                (
                    "file_hash",
                    models.CharField(
                        blank=True,
                        help_text="Para verificar integridad",
                        max_length=64,
                        verbose_name="Hash SHA-256 del archivo",
                    ),
                ),
                (
                    "ocr_text",
                    models.TextField(blank=True, verbose_name="Texto extraído por OCR"),
                ),
                (
                    "ocr_confidence",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=5,
                        null=True,
                        verbose_name="Confianza del OCR (0-100)",
                    ),
                ),
                (
                    "ocr_processed",
                    models.BooleanField(default=False, verbose_name="OCR procesado"),
                ),
                (
                    "ocr_job_id",
                    models.CharField(
                        blank=True, max_length=255, verbose_name="AWS Textract Job ID"
                    ),
                ),
                (
                    "is_signed",
                    models.BooleanField(
                        default=False, verbose_name="Firmado digitalmente"
                    ),
                ),
                (
                    "signed_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Fecha de firma"
                    ),
                ),
                (
                    "digital_signature",
                    models.TextField(blank=True, verbose_name="Firma digital"),
                ),
                (
                    "is_locked",
                    models.BooleanField(
                        default=False,
                        help_text="Los documentos bloqueados no pueden editarse",
                        verbose_name="Bloqueado",
                    ),
                ),
                (
                    "tags",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text='["laboratorio", "urgente"]',
                        verbose_name="Etiquetas",
                    ),
                ),
                (
                    "clinical_record",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="clinical_records.clinicalrecord",
                        verbose_name="Historia clínica",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="documents_created",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Creado por",
                    ),
                ),
                (
                    "signed_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="documents_signed",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Firmado por",
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(class)s_set",
                        to="core.tenant",
                        verbose_name="Tenant",
                    ),
                ),
            ],
            options={
                "verbose_name": "Documento Clínico",
                "verbose_name_plural": "Documentos Clínicos",
                "db_table": "clinical_document",
                "ordering": ["-document_date", "-created_at"],
            },
        ),
        migrations.CreateModel(
            name="MedicalImage",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "deleted_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Fecha de eliminación"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "image_type",
                    models.CharField(
                        choices=[
                            ("xray", "Rayos X"),
                            ("ct_scan", "Tomografía"),
                            ("mri", "Resonancia Magnética"),
                            ("ultrasound", "Ecografía"),
                            ("mammography", "Mamografía"),
                            ("pet_scan", "PET Scan"),
                        ],
                        max_length=100,
                        verbose_name="Tipo de imagen",
                    ),
                ),
                ("title", models.CharField(max_length=255, verbose_name="Título")),
                ("study_date", models.DateTimeField(verbose_name="Fecha del estudio")),
                (
                    "modality",
                    models.CharField(
                        blank=True,
                        help_text="CR, CT, MR, US, etc.",
                        max_length=50,
                        verbose_name="Modalidad DICOM",
                    ),
                ),
                (
                    "body_part",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="Parte del cuerpo"
                    ),
                ),
                (
                    "file_path",
                    models.CharField(
                        max_length=500, verbose_name="Ruta del archivo en S3"
                    ),
                ),
                (
                    "file_name",
                    models.CharField(max_length=255, verbose_name="Nombre del archivo"),
                ),
                (
                    "file_size_bytes",
                    models.BigIntegerField(
                        blank=True, null=True, verbose_name="Tamaño del archivo"
                    ),
                ),
                (
                    "dicom_metadata",
                    models.JSONField(
                        blank=True, default=dict, verbose_name="Metadatos DICOM"
                    ),
                ),
                (
                    "enhanced_image_path",
                    models.CharField(
                        blank=True,
                        max_length=500,
                        verbose_name="Ruta de imagen mejorada",
                    ),
                ),
                (
                    "enhancement_applied",
                    models.BooleanField(default=False, verbose_name="Mejora aplicada"),
                ),
                (
                    "enhancement_params",
                    models.JSONField(
                        blank=True, default=dict, verbose_name="Parámetros de mejora"
                    ),
                ),
                (
                    "clinical_record",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="clinical_records.clinicalrecord",
                        verbose_name="Historia clínica",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Creado por",
                    ),
                ),
                (
                    "document",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="documents.clinicaldocument",
                        verbose_name="Documento asociado",
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(class)s_set",
                        to="core.tenant",
                        verbose_name="Tenant",
                    ),
                ),
            ],
            options={
                "verbose_name": "Imagen Médica",
                "verbose_name_plural": "Imágenes Médicas",
                "db_table": "medical_image",
                "ordering": ["-study_date"],
                "indexes": [
                    models.Index(
                        fields=["tenant", "clinical_record"],
                        name="medical_ima_tenant__6832c9_idx",
                    ),
                    models.Index(
                        fields=["image_type"], name="medical_ima_image_t_f6bc66_idx"
                    ),
                    models.Index(
                        fields=["study_date"], name="medical_ima_study_d_f15c8c_idx"
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="DocumentAccessLog",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "access_type",
                    models.CharField(
                        choices=[
                            ("view", "Visualización"),
                            ("download", "Descarga"),
                            ("print", "Impresión"),
                            ("share", "Compartir"),
                        ],
                        max_length=50,
                        verbose_name="Tipo de acceso",
                    ),
                ),
                (
                    "user_email",
                    models.CharField(max_length=255, verbose_name="Email del usuario"),
                ),
                (
                    "user_name",
                    models.CharField(max_length=255, verbose_name="Nombre del usuario"),
                ),
                (
                    "ip_address",
                    models.GenericIPAddressField(
                        null=True, verbose_name="Dirección IP"
                    ),
                ),
                ("user_agent", models.TextField(blank=True, verbose_name="User Agent")),
                (
                    "access_reason",
                    models.TextField(
                        blank=True,
                        help_text="Justificación opcional",
                        verbose_name="Razón del acceso",
                    ),
                ),
                (
                    "accessed_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Fecha de acceso"
                    ),
                ),
                (
                    "document",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="documents.clinicaldocument",
                        verbose_name="Documento",
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="core.tenant",
                        verbose_name="Tenant",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Usuario",
                    ),
                ),
            ],
            options={
                "verbose_name": "Log de Acceso a Documento",
                "verbose_name_plural": "Logs de Acceso a Documentos",
                "db_table": "document_access_log",
                "ordering": ["-accessed_at"],
                "indexes": [
                    models.Index(
                        fields=["tenant", "document"],
                        name="document_ac_tenant__3bdd12_idx",
                    ),
                    models.Index(
                        fields=["user", "accessed_at"],
                        name="document_ac_user_id_19b1f9_idx",
                    ),
                    models.Index(
                        fields=["accessed_at"], name="document_ac_accesse_3d32df_idx"
                    ),
                ],
            },
        ),
        migrations.AddIndex(
            model_name="clinicaldocument",
            index=models.Index(
                fields=["tenant", "clinical_record"],
                name="clinical_do_tenant__8466fe_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="clinicaldocument",
            index=models.Index(
                fields=["document_type"], name="clinical_do_documen_bdd2b6_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="clinicaldocument",
            index=models.Index(
                fields=["document_date"], name="clinical_do_documen_0277fb_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="clinicaldocument",
            index=models.Index(
                fields=["specialty"], name="clinical_do_special_b89094_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="clinicaldocument",
            index=models.Index(
                fields=["created_at"], name="clinical_do_created_0f40b4_idx"
            ),
        ),
    ]
