# Generated by Django 4.2.7 on 2025-11-16 14:26

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("documents", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="clinicaldocument",
            name="ocr_status",
            field=models.CharField(
                choices=[
                    ("pending", "Pendiente"),
                    ("processing", "Procesando"),
                    ("async_processing", "Procesando (Asíncrono)"),
                    ("completed", "Completado"),
                    ("failed", "Fallido"),
                ],
                default="pending",
                max_length=50,
                verbose_name="Estado del OCR",
            ),
        ),
    ]
