# Generated by Django 4.2.7 on 2025-11-18 20:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0002_clinicaldocument_ocr_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='clinicaldocument',
            name='enhanced_image_path',
            field=models.CharField(blank=True, max_length=500, verbose_name='Ruta de imagen mejorada en S3'),
        ),
    ]
