# Generated by Django 4.2.7 on 2025-11-05 12:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="SubscriptionPlan",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("slug", models.SlugField(unique=True)),
                (
                    "plan_type",
                    models.CharField(
                        choices=[
                            ("basic", "Basic"),
                            ("professional", "Professional"),
                            ("enterprise", "Enterprise"),
                        ],
                        max_length=20,
                    ),
                ),
                ("description", models.TextField()),
                ("monthly_price", models.DecimalField(decimal_places=2, max_digits=10)),
                ("annual_price", models.DecimalField(decimal_places=2, max_digits=10)),
                ("max_users", models.IntegerField()),
                ("max_patients", models.IntegerField()),
                ("storage_gb", models.IntegerField()),
                ("features", models.JSONField(default=list)),
                ("is_active", models.BooleanField(default=True)),
                ("display_order", models.IntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "ordering": ["display_order", "monthly_price"],
            },
        ),
        migrations.CreateModel(
            name="TenantRegistration",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("tenant_name", models.CharField(max_length=200)),
                ("subdomain", models.SlugField(max_length=63, unique=True)),
                ("admin_first_name", models.CharField(max_length=100)),
                ("admin_last_name", models.CharField(max_length=100)),
                ("admin_email", models.EmailField(max_length=254)),
                ("admin_phone", models.CharField(blank=True, max_length=20)),
                (
                    "billing_cycle",
                    models.CharField(
                        choices=[("monthly", "Monthly"), ("annual", "Annual")],
                        max_length=20,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending_payment", "Pending Payment"),
                            ("payment_completed", "Payment Completed"),
                            ("activated", "Activated"),
                            ("failed", "Failed"),
                            ("cancelled", "Cancelled"),
                        ],
                        default="pending_payment",
                        max_length=20,
                    ),
                ),
                ("payment_intent_id", models.CharField(blank=True, max_length=200)),
                (
                    "payment_amount",
                    models.DecimalField(decimal_places=2, max_digits=10),
                ),
                ("payment_completed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "activation_token",
                    models.CharField(blank=True, max_length=100, unique=True),
                ),
                (
                    "activation_email_sent_at",
                    models.DateTimeField(blank=True, null=True),
                ),
                ("activated_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "selected_plan",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="registrations",
                        to="tenants.subscriptionplan",
                    ),
                ),
                (
                    "tenant",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="registration",
                        to="core.tenant",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
    ]
