# Generated by Django 4.2.7 on 2025-11-21 03:32

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("tenants", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="tenantregistration",
            name="activation_token",
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
    ]
