# Generated by Django 4.2.7 on 2025-10-29 02:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Patient",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "deleted_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Fecha de eliminación"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "identity_document_type",
                    models.CharField(
                        choices=[
                            ("CI", "Cédula de Identidad"),
                            ("Pasaporte", "Pasaporte"),
                            ("DNI", "DNI"),
                            ("RUT", "RUT"),
                        ],
                        default="CI",
                        max_length=50,
                        verbose_name="Tipo de documento",
                    ),
                ),
                (
                    "identity_document",
                    models.CharField(
                        max_length=100, verbose_name="Número de documento"
                    ),
                ),
                (
                    "first_name",
                    models.CharField(max_length=100, verbose_name="Nombres"),
                ),
                (
                    "last_name",
                    models.CharField(max_length=100, verbose_name="Apellidos"),
                ),
                ("date_of_birth", models.DateField(verbose_name="Fecha de nacimiento")),
                (
                    "gender",
                    models.CharField(
                        choices=[("M", "Masculino"), ("F", "Femenino"), ("O", "Otro")],
                        max_length=1,
                        verbose_name="Género",
                    ),
                ),
                (
                    "phone",
                    models.CharField(
                        blank=True, max_length=50, verbose_name="Teléfono"
                    ),
                ),
                (
                    "email",
                    models.EmailField(blank=True, max_length=254, verbose_name="Email"),
                ),
                ("address", models.TextField(blank=True, verbose_name="Dirección")),
                (
                    "city",
                    models.CharField(blank=True, max_length=100, verbose_name="Ciudad"),
                ),
                (
                    "emergency_contact",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text='{"name": "...", "relationship": "...", "phone": "..."}',
                        verbose_name="Contacto de emergencia",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="patients_created",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Creado por",
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(class)s_set",
                        to="core.tenant",
                        verbose_name="Tenant",
                    ),
                ),
            ],
            options={
                "verbose_name": "Paciente",
                "verbose_name_plural": "Pacientes",
                "db_table": "patient",
                "indexes": [
                    models.Index(
                        fields=["tenant", "identity_document"],
                        name="patient_tenant__108017_idx",
                    ),
                    models.Index(
                        fields=["first_name", "last_name"],
                        name="patient_first_n_d4c25e_idx",
                    ),
                    models.Index(
                        fields=["created_at"], name="patient_created_98b4e7_idx"
                    ),
                ],
                "unique_together": {("tenant", "identity_document")},
            },
        ),
    ]
