# Generated by Django 4.2.7 on 2025-11-19 02:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("patients", "0001_initial"),
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="AIConversation",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        blank=True,
                        max_length=255,
                        verbose_name="Título de la conversación",
                    ),
                ),
                (
                    "context_type",
                    models.CharField(
                        choices=[
                            ("general", "Ayuda General"),
                            ("patient", "Información Paciente"),
                            ("document", "Análisis Documento"),
                            ("report", "Generación Reporte"),
                        ],
                        default="general",
                        max_length=50,
                        verbose_name="Tipo de contexto",
                    ),
                ),
                (
                    "context_id",
                    models.UUIDField(
                        blank=True,
                        help_text="ID del paciente, documento, etc.",
                        null=True,
                        verbose_name="ID de contexto",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "tenant",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="core.tenant",
                        verbose_name="Tenant",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ai_conversations",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Usuario",
                    ),
                ),
            ],
            options={
                "verbose_name": "Conversación IA",
                "verbose_name_plural": "Conversaciones IA",
                "db_table": "ai_conversations",
                "ordering": ["-updated_at"],
            },
        ),
        migrations.CreateModel(
            name="DiabetesPredictionModel",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "version",
                    models.CharField(
                        help_text="ej: 1.0, 1.1, 2.0",
                        max_length=50,
                        unique=True,
                        verbose_name="Versión del modelo",
                    ),
                ),
                (
                    "model_file",
                    models.CharField(
                        help_text="Ruta relativa al archivo .pkl del modelo",
                        max_length=500,
                        verbose_name="Ruta del archivo del modelo",
                    ),
                ),
                (
                    "algorithm",
                    models.CharField(
                        default="DecisionTreeClassifier",
                        max_length=100,
                        verbose_name="Algoritmo utilizado",
                    ),
                ),
                (
                    "accuracy",
                    models.FloatField(
                        help_text="0.0 a 1.0", verbose_name="Exactitud (Accuracy)"
                    ),
                ),
                (
                    "precision",
                    models.FloatField(help_text="0.0 a 1.0", verbose_name="Precisión"),
                ),
                (
                    "recall",
                    models.FloatField(
                        help_text="0.0 a 1.0", verbose_name="Recall (Sensibilidad)"
                    ),
                ),
                (
                    "f1_score",
                    models.FloatField(help_text="0.0 a 1.0", verbose_name="F1-Score"),
                ),
                (
                    "training_samples",
                    models.IntegerField(
                        help_text="Número de registros usados para entrenar",
                        verbose_name="Muestras de entrenamiento",
                    ),
                ),
                (
                    "test_samples",
                    models.IntegerField(
                        help_text="Número de registros usados para evaluar",
                        verbose_name="Muestras de prueba",
                    ),
                ),
                (
                    "features_used",
                    models.JSONField(
                        default=list,
                        help_text='["age", "bmi", "glucose", ...]',
                        verbose_name="Features utilizadas",
                    ),
                ),
                (
                    "hyperparameters",
                    models.JSONField(
                        default=dict,
                        help_text='{"max_depth": 5, "min_samples_split": 10, ...}',
                        verbose_name="Hiperparámetros",
                    ),
                ),
                (
                    "confusion_matrix",
                    models.JSONField(
                        default=list,
                        help_text="[[TN, FP], [FN, TP]]",
                        verbose_name="Matriz de confusión",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Solo un modelo puede estar activo a la vez",
                        verbose_name="Modelo activo",
                    ),
                ),
                (
                    "notes",
                    models.TextField(
                        blank=True,
                        help_text="Observaciones sobre este modelo",
                        verbose_name="Notas",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "trained_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="diabetes_models_trained",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Entrenado por",
                    ),
                ),
            ],
            options={
                "verbose_name": "Modelo de Predicción de Diabetes",
                "verbose_name_plural": "Modelos de Predicción de Diabetes",
                "db_table": "diabetes_prediction_model",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="DiabetesPrediction",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "has_diabetes_risk",
                    models.BooleanField(
                        help_text="True si el modelo predice riesgo de diabetes",
                        verbose_name="Riesgo de diabetes",
                    ),
                ),
                (
                    "probability",
                    models.FloatField(
                        help_text="Probabilidad de tener diabetes (0.0 a 1.0)",
                        verbose_name="Probabilidad",
                    ),
                ),
                (
                    "risk_level",
                    models.CharField(
                        choices=[
                            ("low", "Bajo"),
                            ("medium", "Medio"),
                            ("high", "Alto"),
                            ("very_high", "Muy Alto"),
                        ],
                        max_length=20,
                        verbose_name="Nivel de riesgo",
                    ),
                ),
                (
                    "input_features",
                    models.JSONField(
                        help_text='{{"age": 45, "bmi": 28.5, "glucose": 140, ...}}',
                        verbose_name="Features de entrada",
                    ),
                ),
                (
                    "contributing_factors",
                    models.JSONField(
                        default=list,
                        help_text='["IMC alto (32.5)", "Glucosa elevada (155)", ...]',
                        verbose_name="Factores contribuyentes",
                    ),
                ),
                (
                    "feature_importance",
                    models.JSONField(
                        default=dict,
                        help_text='{{"glucose": 0.35, "bmi": 0.25, ...}}',
                        verbose_name="Importancia de features",
                    ),
                ),
                (
                    "recommendations",
                    models.JSONField(
                        default=list,
                        help_text='["Control de glucosa mensual", "Reducir peso", ...]',
                        verbose_name="Recomendaciones",
                    ),
                ),
                (
                    "notes",
                    models.TextField(
                        blank=True,
                        help_text="Observaciones del médico sobre la predicción",
                        verbose_name="Notas médicas",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "model",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="predictions",
                        to="ai.diabetespredictionmodel",
                        verbose_name="Modelo utilizado",
                    ),
                ),
                (
                    "patient",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="diabetes_predictions",
                        to="patients.patient",
                        verbose_name="Paciente",
                    ),
                ),
                (
                    "predicted_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="diabetes_predictions_made",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Predicción realizada por",
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="core.tenant",
                        verbose_name="Tenant",
                    ),
                ),
            ],
            options={
                "verbose_name": "Predicción de Diabetes",
                "verbose_name_plural": "Predicciones de Diabetes",
                "db_table": "diabetes_prediction",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="DiabetesDataset",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "source",
                    models.CharField(
                        choices=[
                            ("pima", "Pima Indians Dataset"),
                            ("synthetic", "Datos Sintéticos"),
                            ("clinical", "Datos Clínicos Reales"),
                            ("mixed", "Mixto"),
                        ],
                        max_length=50,
                        verbose_name="Fuente de datos",
                    ),
                ),
                (
                    "pregnancies",
                    models.IntegerField(
                        help_text="0 para hombres", verbose_name="Número de embarazos"
                    ),
                ),
                (
                    "glucose",
                    models.FloatField(verbose_name="Glucosa en plasma (mg/dL)"),
                ),
                (
                    "blood_pressure",
                    models.FloatField(
                        verbose_name="Presión arterial diastólica (mm Hg)"
                    ),
                ),
                (
                    "skin_thickness",
                    models.FloatField(
                        verbose_name="Grosor del pliegue cutáneo del tríceps (mm)"
                    ),
                ),
                (
                    "insulin",
                    models.FloatField(verbose_name="Insulina sérica (mu U/ml)"),
                ),
                (
                    "bmi",
                    models.FloatField(verbose_name="Índice de Masa Corporal (kg/m²)"),
                ),
                (
                    "diabetes_pedigree_function",
                    models.FloatField(
                        help_text="Probabilidad genética de diabetes",
                        verbose_name="Función de pedigrí de diabetes",
                    ),
                ),
                ("age", models.IntegerField(verbose_name="Edad (años)")),
                (
                    "outcome",
                    models.BooleanField(
                        help_text="True = Diabetes, False = No diabetes",
                        verbose_name="Tiene diabetes",
                    ),
                ),
                (
                    "is_training_data",
                    models.BooleanField(
                        default=True,
                        help_text="False si es dato de validación/test",
                        verbose_name="Dato de entrenamiento",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "patient",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="diabetes_dataset_records",
                        to="patients.patient",
                        verbose_name="Paciente (si es dato real)",
                    ),
                ),
            ],
            options={
                "verbose_name": "Registro de Dataset de Diabetes",
                "verbose_name_plural": "Registros de Dataset de Diabetes",
                "db_table": "diabetes_dataset",
                "ordering": ["id"],
            },
        ),
        migrations.CreateModel(
            name="AIMessage",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "role",
                    models.CharField(
                        choices=[
                            ("user", "Usuario"),
                            ("assistant", "Asistente"),
                            ("system", "Sistema"),
                        ],
                        max_length=20,
                        verbose_name="Rol",
                    ),
                ),
                ("content", models.TextField(verbose_name="Contenido del mensaje")),
                (
                    "tokens_used",
                    models.IntegerField(default=0, verbose_name="Tokens utilizados"),
                ),
                (
                    "confidence_score",
                    models.FloatField(
                        default=0.0,
                        help_text="0.0 a 1.0",
                        verbose_name="Confianza de la respuesta",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "conversation",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="messages",
                        to="ai.aiconversation",
                        verbose_name="Conversación",
                    ),
                ),
            ],
            options={
                "verbose_name": "Mensaje IA",
                "verbose_name_plural": "Mensajes IA",
                "db_table": "ai_messages",
                "ordering": ["created_at"],
            },
        ),
        migrations.CreateModel(
            name="AIKnowledgeBase",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "category",
                    models.CharField(
                        help_text="ej: procesos, diagnósticos, etc.",
                        max_length=100,
                        verbose_name="Categoría",
                    ),
                ),
                ("question", models.TextField(verbose_name="Pregunta/Tema")),
                ("answer", models.TextField(verbose_name="Respuesta/Información")),
                (
                    "keywords",
                    models.CharField(
                        blank=True,
                        max_length=500,
                        verbose_name="Palabras clave (separadas por comas)",
                    ),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="Activo")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Base de Conocimiento IA",
                "verbose_name_plural": "Bases de Conocimiento IA",
                "db_table": "ai_knowledge_base",
                "indexes": [
                    models.Index(
                        fields=["category", "is_active"],
                        name="ai_knowledg_categor_86bc83_idx",
                    )
                ],
            },
        ),
        migrations.AddIndex(
            model_name="diabetespredictionmodel",
            index=models.Index(
                fields=["is_active"], name="diabetes_pr_is_acti_74b64f_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="diabetespredictionmodel",
            index=models.Index(
                fields=["version"], name="diabetes_pr_version_e6cb1f_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="diabetesprediction",
            index=models.Index(
                fields=["tenant", "patient"], name="diabetes_pr_tenant__555d46_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="diabetesprediction",
            index=models.Index(
                fields=["risk_level"], name="diabetes_pr_risk_le_fb5798_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="diabetesprediction",
            index=models.Index(
                fields=["-created_at"], name="diabetes_pr_created_f0f6a8_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="diabetesdataset",
            index=models.Index(fields=["source"], name="diabetes_da_source_02a084_idx"),
        ),
        migrations.AddIndex(
            model_name="diabetesdataset",
            index=models.Index(
                fields=["outcome"], name="diabetes_da_outcome_944dfb_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="diabetesdataset",
            index=models.Index(
                fields=["is_training_data"], name="diabetes_da_is_trai_b4cb65_idx"
            ),
        ),
    ]
