# Generated by Django 4.2.7 on 2025-11-05 12:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="AuditLog",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "user_email",
                    models.CharField(max_length=255, verbose_name="Email del usuario"),
                ),
                (
                    "user_name",
                    models.CharField(max_length=255, verbose_name="Nombre del usuario"),
                ),
                (
                    "action_type",
                    models.CharField(
                        choices=[
                            ("CREATE", "Crear"),
                            ("READ", "Leer"),
                            ("UPDATE", "Actualizar"),
                            ("DELETE", "Eliminar"),
                            ("EXPORT", "Exportar"),
                            ("LOGIN", "Login"),
                            ("LOGOUT", "Logout"),
                            ("PASSWORD_CHANGE", "Cambio de Contraseña"),
                            ("PERMISSION_CHANGE", "Cambio de Permisos"),
                            ("SIGN", "Firma Digital"),
                            ("DOWNLOAD", "Descarga"),
                        ],
                        max_length=100,
                        verbose_name="Tipo de acción",
                    ),
                ),
                (
                    "resource_type",
                    models.CharField(
                        help_text="patient, document, user, etc.",
                        max_length=100,
                        verbose_name="Tipo de recurso",
                    ),
                ),
                (
                    "resource_id",
                    models.UUIDField(
                        blank=True, null=True, verbose_name="ID del recurso"
                    ),
                ),
                (
                    "resource_name",
                    models.CharField(
                        blank=True, max_length=255, verbose_name="Nombre del recurso"
                    ),
                ),
                (
                    "ip_address",
                    models.GenericIPAddressField(verbose_name="Dirección IP"),
                ),
                ("user_agent", models.TextField(blank=True, verbose_name="User Agent")),
                (
                    "request_method",
                    models.CharField(
                        blank=True, max_length=10, verbose_name="Método HTTP"
                    ),
                ),
                (
                    "request_path",
                    models.CharField(
                        blank=True, max_length=500, verbose_name="Ruta de la petición"
                    ),
                ),
                (
                    "request_body",
                    models.JSONField(
                        blank=True, default=dict, verbose_name="Cuerpo de la petición"
                    ),
                ),
                (
                    "changes",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text='{"before": {...}, "after": {...}}',
                        verbose_name="Cambios realizados",
                    ),
                ),
                (
                    "response_status",
                    models.IntegerField(
                        blank=True, null=True, verbose_name="Status code de respuesta"
                    ),
                ),
                (
                    "error_message",
                    models.TextField(blank=True, verbose_name="Mensaje de error"),
                ),
                (
                    "session_id",
                    models.UUIDField(
                        blank=True, null=True, verbose_name="ID de sesión"
                    ),
                ),
                (
                    "metadata",
                    models.JSONField(
                        blank=True, default=dict, verbose_name="Metadata adicional"
                    ),
                ),
                (
                    "timestamp",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Fecha y hora"
                    ),
                ),
                (
                    "log_hash",
                    models.CharField(
                        editable=False,
                        help_text="Hash del log para detectar manipulación",
                        max_length=64,
                        verbose_name="Hash SHA-256",
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="core.tenant",
                        verbose_name="Tenant",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Usuario",
                    ),
                ),
            ],
            options={
                "verbose_name": "Log de Auditoría",
                "verbose_name_plural": "Logs de Auditoría",
                "db_table": "audit_log",
                "ordering": ["-timestamp"],
                "indexes": [
                    models.Index(
                        fields=["tenant", "-timestamp"],
                        name="audit_log_tenant__56bf3c_idx",
                    ),
                    models.Index(
                        fields=["user", "-timestamp"],
                        name="audit_log_user_id_79f582_idx",
                    ),
                    models.Index(
                        fields=["resource_type", "resource_id"],
                        name="audit_log_resourc_2570dd_idx",
                    ),
                    models.Index(
                        fields=["action_type"], name="audit_log_action__ff81b5_idx"
                    ),
                    models.Index(
                        fields=["ip_address"], name="audit_log_ip_addr_ef1097_idx"
                    ),
                    models.Index(
                        fields=["-timestamp"], name="audit_log_timesta_8b04a8_idx"
                    ),
                ],
            },
        ),
    ]
