# Generated by Django 4.2.7 on 2025-11-02 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reporttemplate',
            name='output_formats',
            field=models.JSONField(default=list),
        ),
    ]