# Generated by Django 4.2.7 on 2025-11-04 14:27

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0001_initial"),
        ("reports", "0002_alter_reporttemplate_output_formats"),
    ]

    operations = [
        migrations.CreateModel(
            name="AIAnalysis",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "deleted_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Fecha de eliminación"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("analysis", models.TextField()),
                ("insights", models.JSONField(default=list)),
                ("key_findings", models.JSONField(default=list)),
                ("confidence_score", models.FloatField(default=0.0)),
                ("summary", models.TextField(blank=True, null=True)),
                ("summary_key_points", models.JSONField(blank=True, default=list)),
                ("recommendations", models.JSONField(blank=True, default=list)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pendiente"),
                            ("completed", "Completado"),
                            ("failed", "Fallido"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("error_message", models.TextField(blank=True, null=True)),
                (
                    "report_execution",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ai_analysis",
                        to="reports.reportexecution",
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(class)s_set",
                        to="core.tenant",
                        verbose_name="Tenant",
                    ),
                ),
            ],
            options={
                "verbose_name": "AI Analysis",
                "verbose_name_plural": "AI Analyses",
                "db_table": "ai_analysis",
                "indexes": [
                    models.Index(
                        fields=["report_execution", "-created_at"],
                        name="ai_analysis_report__7a08bd_idx",
                    ),
                    models.Index(
                        fields=["status"], name="ai_analysis_status_a16618_idx"
                    ),
                ],
            },
        ),
    ]
