# Generated by Django 4.2.7 on 2025-11-04 16:42

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("reports", "0003_aianalysis"),
    ]

    operations = [
        migrations.AddField(
            model_name="reportexecution",
            name="report_type",
            field=models.CharField(
                blank=True,
                choices=[
                    ("documents", "Documentos Clínicos"),
                    ("patients", "Pacientes"),
                    ("clinical_records", "Historias Clínicas"),
                    ("analytics", "Analíticas"),
                    ("audit", "Auditoría"),
                    ("users", "Usuarios"),
                ],
                default="documents",
                max_length=50,
            ),
        ),
    ]
