# Generated by Django 4.2.7 on 2025-11-23 17:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("core", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("patients", "0001_initial"),
        ("clinical_records", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="DicomStudy",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "deleted_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Fecha de eliminación"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "study_instance_uid",
                    models.CharField(
                        help_text="Identificador único DICOM del estudio",
                        max_length=128,
                        unique=True,
                        verbose_name="Study Instance UID",
                    ),
                ),
                (
                    "accession_number",
                    models.CharField(
                        blank=True,
                        help_text="Número de acceso del estudio",
                        max_length=64,
                        verbose_name="Accession Number",
                    ),
                ),
                (
                    "study_date",
                    models.DateField(
                        blank=True, null=True, verbose_name="Fecha del Estudio"
                    ),
                ),
                (
                    "study_time",
                    models.TimeField(
                        blank=True, null=True, verbose_name="Hora del Estudio"
                    ),
                ),
                (
                    "study_description",
                    models.CharField(
                        blank=True,
                        max_length=255,
                        verbose_name="Descripción del Estudio",
                    ),
                ),
                (
                    "modality",
                    models.CharField(
                        choices=[
                            ("CR", "Computed Radiography"),
                            ("CT", "Computed Tomography"),
                            ("MR", "Magnetic Resonance"),
                            ("US", "Ultrasound"),
                            ("XA", "X-Ray Angiography"),
                            ("MG", "Mammography"),
                            ("PT", "PET Scan"),
                            ("NM", "Nuclear Medicine"),
                            ("DX", "Digital Radiography"),
                            ("OT", "Other"),
                        ],
                        default="OT",
                        help_text="Modalidad principal del estudio",
                        max_length=16,
                        verbose_name="Modalidad Principal",
                    ),
                ),
                (
                    "body_part_examined",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="Parte del Cuerpo"
                    ),
                ),
                (
                    "referring_physician_name",
                    models.CharField(
                        blank=True, max_length=255, verbose_name="Médico Referente"
                    ),
                ),
                (
                    "institution_name",
                    models.CharField(
                        blank=True, max_length=255, verbose_name="Institución"
                    ),
                ),
                (
                    "number_of_series",
                    models.PositiveIntegerField(
                        default=0, verbose_name="Número de Series"
                    ),
                ),
                (
                    "number_of_instances",
                    models.PositiveIntegerField(
                        default=0, verbose_name="Número de Instancias"
                    ),
                ),
                (
                    "total_size_bytes",
                    models.BigIntegerField(
                        default=0, verbose_name="Tamaño Total (bytes)"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("uploading", "Subiendo"),
                            ("processing", "Procesando"),
                            ("completed", "Completado"),
                            ("failed", "Fallido"),
                        ],
                        default="uploading",
                        max_length=20,
                        verbose_name="Estado",
                    ),
                ),
                (
                    "processing_error",
                    models.TextField(blank=True, verbose_name="Error de Procesamiento"),
                ),
                (
                    "dicom_metadata",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Metadata completa del estudio en formato JSON",
                        verbose_name="Metadatos DICOM",
                    ),
                ),
                (
                    "study_hash",
                    models.CharField(
                        blank=True,
                        help_text="Hash para verificar integridad del estudio",
                        max_length=64,
                        verbose_name="Hash SHA-256",
                    ),
                ),
                (
                    "clinical_record",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="dicom_studies",
                        to="clinical_records.clinicalrecord",
                        verbose_name="Historia Clínica",
                    ),
                ),
                (
                    "patient",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="dicom_studies",
                        to="patients.patient",
                        verbose_name="Paciente",
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(class)s_set",
                        to="core.tenant",
                        verbose_name="Tenant",
                    ),
                ),
                (
                    "uploaded_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="dicom_studies_uploaded",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Subido por",
                    ),
                ),
            ],
            options={
                "verbose_name": "Estudio DICOM",
                "verbose_name_plural": "Estudios DICOM",
                "db_table": "dicom_study",
                "ordering": ["-study_date", "-created_at"],
            },
        ),
        migrations.CreateModel(
            name="DicomSeries",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "deleted_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Fecha de eliminación"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "series_instance_uid",
                    models.CharField(
                        help_text="Identificador único DICOM de la serie",
                        max_length=128,
                        unique=True,
                        verbose_name="Series Instance UID",
                    ),
                ),
                (
                    "series_number",
                    models.PositiveIntegerField(
                        blank=True, null=True, verbose_name="Número de Serie"
                    ),
                ),
                (
                    "series_description",
                    models.CharField(
                        blank=True,
                        max_length=255,
                        verbose_name="Descripción de la Serie",
                    ),
                ),
                (
                    "modality",
                    models.CharField(
                        blank=True,
                        help_text="Modalidad específica de esta serie",
                        max_length=16,
                        verbose_name="Modalidad",
                    ),
                ),
                (
                    "series_date",
                    models.DateField(
                        blank=True, null=True, verbose_name="Fecha de la Serie"
                    ),
                ),
                (
                    "series_time",
                    models.TimeField(
                        blank=True, null=True, verbose_name="Hora de la Serie"
                    ),
                ),
                (
                    "slice_thickness",
                    models.DecimalField(
                        blank=True,
                        decimal_places=4,
                        max_digits=10,
                        null=True,
                        verbose_name="Espesor del Corte (mm)",
                    ),
                ),
                (
                    "pixel_spacing",
                    models.CharField(
                        blank=True,
                        help_text='Formato: "row_spacing\\column_spacing" en mm',
                        max_length=50,
                        verbose_name="Espaciado de Píxeles",
                    ),
                ),
                (
                    "image_orientation_patient",
                    models.CharField(
                        blank=True,
                        help_text="Cosenos directores de fila y columna",
                        max_length=100,
                        verbose_name="Orientación de Imagen",
                    ),
                ),
                (
                    "number_of_instances",
                    models.PositiveIntegerField(
                        default=0, verbose_name="Número de Instancias"
                    ),
                ),
                (
                    "total_size_bytes",
                    models.BigIntegerField(
                        default=0, verbose_name="Tamaño Total (bytes)"
                    ),
                ),
                (
                    "dicom_metadata",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        verbose_name="Metadatos DICOM de la Serie",
                    ),
                ),
                (
                    "study",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="series",
                        to="dicom.dicomstudy",
                        verbose_name="Estudio",
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(class)s_set",
                        to="core.tenant",
                        verbose_name="Tenant",
                    ),
                ),
            ],
            options={
                "verbose_name": "Serie DICOM",
                "verbose_name_plural": "Series DICOM",
                "db_table": "dicom_series",
                "ordering": ["series_number", "created_at"],
            },
        ),
        migrations.CreateModel(
            name="DicomInstance",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "deleted_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Fecha de eliminación"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "sop_instance_uid",
                    models.CharField(
                        help_text="Identificador único DICOM de la instancia",
                        max_length=128,
                        unique=True,
                        verbose_name="SOP Instance UID",
                    ),
                ),
                (
                    "sop_class_uid",
                    models.CharField(
                        blank=True,
                        help_text="Tipo de objeto DICOM",
                        max_length=128,
                        verbose_name="SOP Class UID",
                    ),
                ),
                (
                    "instance_number",
                    models.PositiveIntegerField(
                        blank=True,
                        help_text="Posición del frame en la serie",
                        null=True,
                        verbose_name="Número de Instancia",
                    ),
                ),
                (
                    "file_path",
                    models.CharField(
                        help_text="Ruta relativa al MEDIA_ROOT o URL de S3",
                        max_length=500,
                        verbose_name="Ruta del Archivo",
                    ),
                ),
                (
                    "file_name",
                    models.CharField(max_length=255, verbose_name="Nombre del Archivo"),
                ),
                (
                    "file_size_bytes",
                    models.BigIntegerField(
                        default=0, verbose_name="Tamaño del Archivo (bytes)"
                    ),
                ),
                (
                    "file_hash",
                    models.CharField(
                        blank=True,
                        help_text="Hash para verificar integridad del archivo",
                        max_length=64,
                        verbose_name="Hash SHA-256",
                    ),
                ),
                (
                    "rows",
                    models.PositiveIntegerField(
                        blank=True, null=True, verbose_name="Filas (altura)"
                    ),
                ),
                (
                    "columns",
                    models.PositiveIntegerField(
                        blank=True, null=True, verbose_name="Columnas (ancho)"
                    ),
                ),
                (
                    "bits_allocated",
                    models.PositiveSmallIntegerField(
                        blank=True, null=True, verbose_name="Bits Allocados"
                    ),
                ),
                (
                    "bits_stored",
                    models.PositiveSmallIntegerField(
                        blank=True, null=True, verbose_name="Bits Almacenados"
                    ),
                ),
                (
                    "photometric_interpretation",
                    models.CharField(
                        blank=True,
                        help_text="MONOCHROME1, MONOCHROME2, RGB, etc.",
                        max_length=50,
                        verbose_name="Interpretación Fotométrica",
                    ),
                ),
                (
                    "image_position_patient",
                    models.CharField(
                        blank=True,
                        help_text="Coordenadas x, y, z del primer píxel",
                        max_length=100,
                        verbose_name="Posición de Imagen",
                    ),
                ),
                (
                    "slice_location",
                    models.DecimalField(
                        blank=True,
                        decimal_places=6,
                        help_text="Posición relativa del corte en mm",
                        max_digits=15,
                        null=True,
                        verbose_name="Ubicación del Corte",
                    ),
                ),
                (
                    "window_center",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=10,
                        null=True,
                        verbose_name="Window Center",
                    ),
                ),
                (
                    "window_width",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=10,
                        null=True,
                        verbose_name="Window Width",
                    ),
                ),
                (
                    "transfer_syntax_uid",
                    models.CharField(
                        blank=True,
                        help_text="Codificación del archivo DICOM",
                        max_length=128,
                        verbose_name="Transfer Syntax UID",
                    ),
                ),
                (
                    "dicom_metadata",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        verbose_name="Metadatos DICOM de la Instancia",
                    ),
                ),
                (
                    "series",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="instances",
                        to="dicom.dicomseries",
                        verbose_name="Serie",
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(class)s_set",
                        to="core.tenant",
                        verbose_name="Tenant",
                    ),
                ),
            ],
            options={
                "verbose_name": "Instancia DICOM",
                "verbose_name_plural": "Instancias DICOM",
                "db_table": "dicom_instance",
                "ordering": ["instance_number", "slice_location"],
            },
        ),
        migrations.CreateModel(
            name="DicomAccessLog",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "access_type",
                    models.CharField(
                        choices=[
                            ("view", "Visualización"),
                            ("download", "Descarga"),
                            ("stream", "Streaming"),
                            ("export", "Exportación"),
                        ],
                        max_length=20,
                        verbose_name="Tipo de Acceso",
                    ),
                ),
                (
                    "user_email",
                    models.CharField(max_length=255, verbose_name="Email del Usuario"),
                ),
                (
                    "user_name",
                    models.CharField(max_length=255, verbose_name="Nombre del Usuario"),
                ),
                (
                    "ip_address",
                    models.GenericIPAddressField(
                        null=True, verbose_name="Dirección IP"
                    ),
                ),
                ("user_agent", models.TextField(blank=True, verbose_name="User Agent")),
                (
                    "accessed_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Fecha de Acceso"
                    ),
                ),
                (
                    "log_hash",
                    models.CharField(
                        blank=True, max_length=64, verbose_name="Hash del Log"
                    ),
                ),
                (
                    "study",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="access_logs",
                        to="dicom.dicomstudy",
                        verbose_name="Estudio",
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="core.tenant",
                        verbose_name="Tenant",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Usuario",
                    ),
                ),
            ],
            options={
                "verbose_name": "Log de Acceso DICOM",
                "verbose_name_plural": "Logs de Acceso DICOM",
                "db_table": "dicom_access_log",
                "ordering": ["-accessed_at"],
            },
        ),
        migrations.AddIndex(
            model_name="dicomstudy",
            index=models.Index(
                fields=["tenant", "patient"], name="dicom_study_tenant__07375b_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="dicomstudy",
            index=models.Index(
                fields=["study_instance_uid"], name="dicom_study_study_i_71786e_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="dicomstudy",
            index=models.Index(
                fields=["study_date"], name="dicom_study_study_d_2b35e9_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="dicomstudy",
            index=models.Index(
                fields=["modality"], name="dicom_study_modalit_0115a9_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="dicomstudy",
            index=models.Index(fields=["status"], name="dicom_study_status_4c2285_idx"),
        ),
        migrations.AddIndex(
            model_name="dicomstudy",
            index=models.Index(
                fields=["accession_number"], name="dicom_study_accessi_f2e008_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="dicomseries",
            index=models.Index(
                fields=["tenant", "study"], name="dicom_serie_tenant__2b865a_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="dicomseries",
            index=models.Index(
                fields=["series_instance_uid"], name="dicom_serie_series__112155_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="dicomseries",
            index=models.Index(
                fields=["series_number"], name="dicom_serie_series__180404_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="dicomseries",
            index=models.Index(
                fields=["modality"], name="dicom_serie_modalit_0c710c_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="dicominstance",
            index=models.Index(
                fields=["tenant", "series"], name="dicom_insta_tenant__ba2e67_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="dicominstance",
            index=models.Index(
                fields=["sop_instance_uid"], name="dicom_insta_sop_ins_80888e_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="dicominstance",
            index=models.Index(
                fields=["instance_number"], name="dicom_insta_instanc_7705a5_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="dicominstance",
            index=models.Index(
                fields=["slice_location"], name="dicom_insta_slice_l_11ad16_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="dicomaccesslog",
            index=models.Index(
                fields=["tenant", "study"], name="dicom_acces_tenant__ae15b8_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="dicomaccesslog",
            index=models.Index(
                fields=["user", "accessed_at"], name="dicom_acces_user_id_00ab94_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="dicomaccesslog",
            index=models.Index(
                fields=["accessed_at"], name="dicom_acces_accesse_1a010e_idx"
            ),
        ),
    ]
