# Generated by Django 4.2.7 on 2025-11-23 18:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("documents", "0003_clinicaldocument_enhanced_image_path"),
        ("dicom", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="dicomseries",
            name="body_part_examined",
            field=models.CharField(
                blank=True, max_length=100, verbose_name="Parte del Cuerpo Examinada"
            ),
        ),
        migrations.AddField(
            model_name="dicomseries",
            name="contrast_agent",
            field=models.CharField(
                blank=True,
                help_text="Nombre del medio de contraste utilizado",
                max_length=255,
                verbose_name="Agente de Contraste",
            ),
        ),
        migrations.AddField(
            model_name="dicomseries",
            name="has_contrast",
            field=models.BooleanField(
                default=False,
                help_text="Indica si la serie fue adquirida con medio de contraste",
                verbose_name="Con Contraste",
            ),
        ),
        migrations.AddField(
            model_name="dicomstudy",
            name="medical_image",
            field=models.ForeignKey(
                blank=True,
                help_text="Enlace opcional al registro de MedicalImage para compatibilidad",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="dicom_studies",
                to="documents.medicalimage",
                verbose_name="Imagen Médica Asociada",
            ),
        ),
    ]
