# Generated by Django 4.2.7 on 2025-11-04 17:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("core", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Notification",
            fields=[
                (
                    "deleted_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Fecha de eliminación"
                    ),
                ),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, primary_key=True, serialize=False
                    ),
                ),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("appointment.created", "Cita creada"),
                            ("appointment.canceled", "Cita cancelada"),
                            ("appointment.reminder", "Recordatorio de cita"),
                            ("clinical_record.result", "Resultado clínico"),
                            ("inventory.low_stock", "Stock bajo"),
                            ("document.uploaded", "Documento cargado"),
                            ("user.added", "Usuario agregado"),
                            ("system.alert", "Alerta del sistema"),
                        ],
                        db_index=True,
                        max_length=50,
                    ),
                ),
                (
                    "channel",
                    models.CharField(
                        choices=[
                            ("in_app", "En aplicación"),
                            ("email", "Correo electrónico"),
                            ("push", "Notificación push (móvil)"),
                        ],
                        default="in_app",
                        max_length=20,
                    ),
                ),
                ("title", models.CharField(max_length=70)),
                ("body", models.CharField(max_length=300)),
                ("data", models.JSONField(blank=True, default=dict)),
                ("extra_metadata", models.JSONField(blank=True, default=dict)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("queued", "Encolada"),
                            ("sent", "Enviada"),
                            ("delivered", "Entregada"),
                            ("failed", "Falló"),
                            ("read", "Leída"),
                        ],
                        db_index=True,
                        default="queued",
                        max_length=20,
                    ),
                ),
                (
                    "event_id",
                    models.CharField(
                        db_index=True,
                        help_text="ID único del evento para evitar duplicados",
                        max_length=255,
                        unique=True,
                    ),
                ),
                ("sent_at", models.DateTimeField(blank=True, null=True)),
                ("read_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("retry_count", models.PositiveIntegerField(default=0)),
                ("last_error", models.TextField(blank=True, null=True)),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(class)s_set",
                        to="core.tenant",
                        verbose_name="Tenant",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="notifications",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "notification",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="UserNotificationPreferences",
            fields=[
                (
                    "deleted_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Fecha de eliminación"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, primary_key=True, serialize=False
                    ),
                ),
                (
                    "preferences",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Matriz de tipos × canales con opt-in/out",
                    ),
                ),
                ("quiet_hours_enabled", models.BooleanField(default=False)),
                (
                    "quiet_hours_from",
                    models.TimeField(
                        blank=True,
                        help_text="Hora de inicio del silencio (HH:MM)",
                        null=True,
                    ),
                ),
                (
                    "quiet_hours_to",
                    models.TimeField(
                        blank=True,
                        help_text="Hora de fin del silencio (HH:MM)",
                        null=True,
                    ),
                ),
                (
                    "email_digest_enabled",
                    models.BooleanField(
                        default=False,
                        help_text="Agrupar notificaciones en resumen diario",
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(class)s_set",
                        to="core.tenant",
                        verbose_name="Tenant",
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="notification_preferences",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "user_notification_preferences",
            },
        ),
        migrations.CreateModel(
            name="NotificationAudit",
            fields=[
                (
                    "deleted_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Fecha de eliminación"
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, primary_key=True, serialize=False
                    ),
                ),
                (
                    "action",
                    models.CharField(
                        choices=[
                            ("created", "Creada"),
                            ("sent", "Enviada"),
                            ("delivered", "Entregada"),
                            ("failed", "Falló"),
                            ("duplicate_ignored", "Duplicado ignorado"),
                            ("tenant_mismatch", "Aislamiento tenant"),
                            ("preference_skipped", "Omitida por preferencia"),
                            ("quiet_hours", "Omitida por horario"),
                            ("read", "Leída"),
                        ],
                        max_length=50,
                    ),
                ),
                ("detail", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "notification",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="audit_logs",
                        to="notifications.notification",
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(class)s_set",
                        to="core.tenant",
                        verbose_name="Tenant",
                    ),
                ),
            ],
            options={
                "db_table": "notification_audit",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["tenant", "notification", "action"],
                        name="notificatio_tenant__44ead4_idx",
                    ),
                    models.Index(
                        fields=["tenant", "created_at"],
                        name="notificatio_tenant__9e71a6_idx",
                    ),
                ],
            },
        ),
        migrations.AddIndex(
            model_name="notification",
            index=models.Index(
                fields=["tenant", "user", "status"],
                name="notificatio_tenant__0c0cc9_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="notification",
            index=models.Index(
                fields=["tenant", "user", "read_at"],
                name="notificatio_tenant__f9f883_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="notification",
            index=models.Index(
                fields=["tenant", "type"], name="notificatio_tenant__f3a523_idx"
            ),
        ),
    ]
